/**
 * Ant Design's per-component token catalog (component name, field name, label, description),
 * generated from each component's own shipped `ComponentToken` interface
 * (`node_modules/antd/es/<dir>/style/{token,index}.d.ts`) by
 * `scripts/extract-component-token-schema.mjs`. No default value is recorded — unlike global
 * seed tokens, antd computes component tokens at render time from the current seed/alias
 * tokens, so an unset field simply means "inherits the computed default" (see build-manifest.ts).
 * Regenerate with `node scripts/extract-component-token-schema.mjs` after bumping antd's
 * version — not run at end-user install time, same pattern as token-schema.generated.ts.
 */
export type ComponentTokenValueType = 'color-hex' | 'number' | 'boolean' | 'string'

export type ComponentTokenSchemaEntry = {
  name: string
  valueType: ComponentTokenValueType
  label: string
  description?: string
}

export type ComponentTokenGroup = {
  /** Registry slug, e.g. 'input-number' — matches COMPONENTS keys in src/generated/registry.ts. */
  slug: string
  /** Real Ant Design component name, e.g. 'InputNumber' — the key under theme.components. */
  component: string
  title: string
  fields: ComponentTokenSchemaEntry[]
}

export const COMPONENT_TOKEN_SCHEMA: ComponentTokenGroup[] = [
  {
    slug: "affix",
    component: "Affix",
    title: "Affix",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of popup" },
    ],
  },
  {
    slug: "alert",
    component: "Alert",
    title: "Alert",
    fields: [
      { name: "defaultPadding", valueType: "string", label: "Default Padding",
        description: "Default padding" },
      { name: "withDescriptionPadding", valueType: "string", label: "With Description Padding",
        description: "Padding with description" },
      { name: "withDescriptionIconSize", valueType: "string", label: "With Description Icon Size",
        description: "Icon size with description" },
    ],
  },
  {
    slug: "anchor",
    component: "Anchor",
    title: "Anchor",
    fields: [
      { name: "linkPaddingBlock", valueType: "number", label: "Link Padding Block",
        description: "Vertical padding of link" },
      { name: "linkPaddingInlineStart", valueType: "number", label: "Link Padding Inline Start",
        description: "Horizontal padding of link" },
    ],
  },
  {
    slug: "avatar",
    component: "Avatar",
    title: "Avatar",
    fields: [
      { name: "containerSize", valueType: "number", label: "Container Size",
        description: "Size of Avatar" },
      { name: "containerSizeLG", valueType: "number", label: "Container Size LG",
        description: "Size of large Avatar" },
      { name: "containerSizeSM", valueType: "number", label: "Container Size SM",
        description: "Size of small Avatar" },
      { name: "textFontSize", valueType: "number", label: "Text Font Size",
        description: "Font size of Avatar" },
      { name: "textFontSizeLG", valueType: "number", label: "Text Font Size LG",
        description: "Font size of large Avatar" },
      { name: "textFontSizeSM", valueType: "number", label: "Text Font Size SM",
        description: "Font size of small Avatar" },
      { name: "iconFontSize", valueType: "number", label: "Icon Font Size",
        description: "Font size of Avatar icon" },
      { name: "iconFontSizeLG", valueType: "string", label: "Icon Font Size LG",
        description: "Font size of large Avatar icon" },
      { name: "iconFontSizeSM", valueType: "number", label: "Icon Font Size SM",
        description: "Font size of small Avatar icon" },
      { name: "groupSpace", valueType: "number", label: "Group Space",
        description: "Spacing between avatars in a group" },
      { name: "groupOverlapping", valueType: "number", label: "Group Overlapping",
        description: "Overlapping of avatars in a group" },
      { name: "groupBorderColor", valueType: "color-hex", label: "Group Border Color",
        description: "Border color of avatars in a group" },
    ],
  },
  {
    slug: "badge",
    component: "Badge",
    title: "Badge",
    fields: [
      { name: "indicatorZIndex", valueType: "string", label: "Indicator ZIndex",
        description: "z-index of badge" },
      { name: "indicatorHeight", valueType: "string", label: "Indicator Height",
        description: "Height of badge" },
      { name: "indicatorHeightSM", valueType: "string", label: "Indicator Height SM",
        description: "Height of small badge" },
      { name: "dotSize", valueType: "number", label: "Dot Size",
        description: "Size of dot badge" },
      { name: "textFontSize", valueType: "number", label: "Text Font Size",
        description: "Font size of badge text" },
      { name: "textFontSizeSM", valueType: "number", label: "Text Font Size SM",
        description: "Font size of small badge text" },
      { name: "textFontWeight", valueType: "string", label: "Text Font Weight",
        description: "Font weight of badge text" },
      { name: "statusSize", valueType: "number", label: "Status Size",
        description: "Size of status badge" },
      { name: "paddingInline", valueType: "string", label: "Padding Inline",
        description: "Inline padding of multiple words badge" },
    ],
  },
  {
    slug: "breadcrumb",
    component: "Breadcrumb",
    title: "Breadcrumb",
    fields: [
      { name: "itemColor", valueType: "color-hex", label: "Item Color",
        description: "Text color of Breadcrumb item" },
      { name: "iconFontSize", valueType: "number", label: "Icon Font Size",
        description: "Icon size" },
      { name: "linkColor", valueType: "color-hex", label: "Link Color",
        description: "Text color of link" },
      { name: "linkHoverColor", valueType: "color-hex", label: "Link Hover Color",
        description: "Color of hovered link" },
      { name: "lastItemColor", valueType: "color-hex", label: "Last Item Color",
        description: "Text color of the last item" },
      { name: "separatorMargin", valueType: "number", label: "Separator Margin",
        description: "Margin of separator" },
      { name: "separatorColor", valueType: "color-hex", label: "Separator Color",
        description: "Color of separator" },
    ],
  },
  {
    slug: "button",
    component: "Button",
    title: "Button",
    fields: [
      { name: "fontWeight", valueType: "string", label: "Font Weight",
        description: "Font weight of text" },
      { name: "iconGap", valueType: "string", label: "Icon Gap",
        description: "Gap between icon and text" },
      { name: "defaultShadow", valueType: "string", label: "Default Shadow",
        description: "Shadow of default button" },
      { name: "primaryShadow", valueType: "string", label: "Primary Shadow",
        description: "Shadow of primary button" },
      { name: "dangerShadow", valueType: "string", label: "Danger Shadow",
        description: "Shadow of danger button" },
      { name: "primaryColor", valueType: "color-hex", label: "Primary Color",
        description: "Text color of primary button" },
      { name: "defaultColor", valueType: "color-hex", label: "Default Color",
        description: "Text color of default button" },
      { name: "defaultBg", valueType: "color-hex", label: "Default Bg",
        description: "Background color of default button" },
      { name: "defaultBorderColor", valueType: "color-hex", label: "Default Border Color",
        description: "Border color of default button" },
      { name: "dangerColor", valueType: "color-hex", label: "Danger Color",
        description: "Text color of danger button" },
      { name: "defaultHoverBg", valueType: "color-hex", label: "Default Hover Bg",
        description: "Background color of default button when hover" },
      { name: "defaultHoverColor", valueType: "color-hex", label: "Default Hover Color",
        description: "Text color of default button when hover" },
      { name: "defaultHoverBorderColor", valueType: "color-hex", label: "Default Hover Border Color",
        description: "Border color of default button" },
      { name: "defaultActiveBg", valueType: "color-hex", label: "Default Active Bg",
        description: "Background color of default button when active" },
      { name: "defaultActiveColor", valueType: "color-hex", label: "Default Active Color",
        description: "Text color of default button when active" },
      { name: "defaultActiveBorderColor", valueType: "color-hex", label: "Default Active Border Color",
        description: "Border color of default button when active" },
      { name: "defaultGhostColor", valueType: "color-hex", label: "Default Ghost Color",
        description: "Text color of default ghost button" },
      { name: "ghostBg", valueType: "color-hex", label: "Ghost Bg",
        description: "Background color of ghost button" },
      { name: "defaultGhostBorderColor", valueType: "color-hex", label: "Default Ghost Border Color",
        description: "Border color of default ghost button" },
      { name: "solidTextColor", valueType: "color-hex", label: "Solid Text Color",
        description: "Background color of primary filled button" },
      { name: "textTextColor", valueType: "color-hex", label: "Text Text Color",
        description: "Default text color for text buttons" },
      { name: "textTextHoverColor", valueType: "color-hex", label: "Text Text Hover Color",
        description: "Default text color for text buttons on hover" },
      { name: "textTextActiveColor", valueType: "color-hex", label: "Text Text Active Color",
        description: "Default text color for text buttons on active" },
      { name: "paddingInline", valueType: "string", label: "Padding Inline",
        description: "Horizontal padding of button" },
      { name: "paddingInlineLG", valueType: "string", label: "Padding Inline LG",
        description: "Horizontal padding of large button" },
      { name: "paddingInlineSM", valueType: "string", label: "Padding Inline SM",
        description: "Horizontal padding of small button" },
      { name: "onlyIconSize", valueType: "string", label: "Only Icon Size",
        description: "Icon size of button which only contains icon" },
      { name: "onlyIconSizeLG", valueType: "string", label: "Only Icon Size LG",
        description: "Icon size of large button which only contains icon" },
      { name: "onlyIconSizeSM", valueType: "string", label: "Only Icon Size SM",
        description: "Icon size of small button which only contains icon" },
      { name: "linkHoverBg", valueType: "color-hex", label: "Link Hover Bg",
        description: "Background color of link button when hover" },
      { name: "textHoverBg", valueType: "color-hex", label: "Text Hover Bg",
        description: "Background color of text button when hover" },
      { name: "contentFontSize", valueType: "number", label: "Content Font Size",
        description: "Font size of button content" },
      { name: "contentFontSizeLG", valueType: "number", label: "Content Font Size LG",
        description: "Font size of large button content" },
      { name: "contentFontSizeSM", valueType: "number", label: "Content Font Size SM",
        description: "Font size of small button content" },
      { name: "defaultBgDisabled", valueType: "color-hex", label: "Default Bg Disabled" },
      { name: "dashedBgDisabled", valueType: "color-hex", label: "Dashed Bg Disabled" },
    ],
  },
  {
    slug: "calendar",
    component: "Calendar",
    title: "Calendar",
    fields: [
      { name: "yearControlWidth", valueType: "string", label: "Year Control Width",
        description: "Width of year select" },
      { name: "monthControlWidth", valueType: "string", label: "Month Control Width",
        description: "Width of month select" },
      { name: "miniContentHeight", valueType: "string", label: "Mini Content Height",
        description: "Height of mini calendar content" },
      { name: "fullBg", valueType: "color-hex", label: "Full Bg",
        description: "Background color of full calendar" },
      { name: "fullPanelBg", valueType: "color-hex", label: "Full Panel Bg",
        description: "Background color of full calendar panel" },
      { name: "itemActiveBg", valueType: "color-hex", label: "Item Active Bg",
        description: "Background color of selected date item" },
    ],
  },
  {
    slug: "card",
    component: "Card",
    title: "Card",
    fields: [
      { name: "headerBg", valueType: "color-hex", label: "Header Bg",
        description: "Background color of card header" },
      { name: "headerFontSize", valueType: "string", label: "Header Font Size",
        description: "Font size of card header" },
      { name: "headerFontSizeSM", valueType: "string", label: "Header Font Size SM",
        description: "Font size of small card header" },
      { name: "headerHeight", valueType: "string", label: "Header Height",
        description: "Height of card header" },
      { name: "headerHeightSM", valueType: "string", label: "Header Height SM",
        description: "Height of small card header" },
      { name: "bodyPaddingSM", valueType: "number", label: "Body Padding SM",
        description: "Padding of small card body" },
      { name: "headerPaddingSM", valueType: "number", label: "Header Padding SM",
        description: "Padding of small card head" },
      { name: "bodyPadding", valueType: "number", label: "Body Padding",
        description: "Padding of card body" },
      { name: "headerPadding", valueType: "number", label: "Header Padding",
        description: "Padding of card head" },
      { name: "actionsBg", valueType: "color-hex", label: "Actions Bg",
        description: "Background color of card actions" },
      { name: "actionsLiMargin", valueType: "string", label: "Actions Li Margin",
        description: "Margin of each item in card actions" },
      { name: "tabsMarginBottom", valueType: "number", label: "Tabs Margin Bottom",
        description: "Margin bottom of tabs component" },
      { name: "extraColor", valueType: "color-hex", label: "Extra Color",
        description: "Text color of extra area" },
    ],
  },
  {
    slug: "carousel",
    component: "Carousel",
    title: "Carousel",
    fields: [
      { name: "dotWidth", valueType: "string", label: "Dot Width",
        description: "Width of indicator" },
      { name: "dotHeight", valueType: "string", label: "Dot Height",
        description: "Height of indicator" },
      { name: "dotGap", valueType: "number", label: "Dot Gap",
        description: "gap between indicator" },
      { name: "dotOffset", valueType: "number", label: "Dot Offset",
        description: "dot offset to Carousel edge" },
      { name: "dotActiveWidth", valueType: "string", label: "Dot Active Width",
        description: "Width of active indicator" },
      { name: "arrowSize", valueType: "number", label: "Arrow Size",
        description: "Size of arrows" },
      { name: "arrowOffset", valueType: "number", label: "Arrow Offset",
        description: "arrows offset to Carousel edge" },
    ],
  },
  {
    slug: "cascader",
    component: "Cascader",
    title: "Cascader",
    fields: [
      { name: "controlWidth", valueType: "string", label: "Control Width",
        description: "Width of Cascader" },
      { name: "controlItemWidth", valueType: "string", label: "Control Item Width",
        description: "Width of item" },
      { name: "dropdownHeight", valueType: "string", label: "Dropdown Height",
        description: "Height of dropdown" },
      { name: "optionSelectedBg", valueType: "color-hex", label: "Option Selected Bg",
        description: "Background color of selected item" },
      { name: "optionSelectedColor", valueType: "color-hex", label: "Option Selected Color",
        description: "Text color when option is selected" },
      { name: "optionSelectedFontWeight", valueType: "string", label: "Option Selected Font Weight",
        description: "Font weight of selected item" },
      { name: "optionPadding", valueType: "string", label: "Option Padding",
        description: "Padding of menu item" },
      { name: "menuPadding", valueType: "string", label: "Menu Padding",
        description: "Padding of menu item (single column)" },
    ],
  },
  {
    slug: "collapse",
    component: "Collapse",
    title: "Collapse",
    fields: [
      { name: "headerPadding", valueType: "string", label: "Header Padding",
        description: "Padding of header" },
      { name: "headerPaddingSM", valueType: "string", label: "Header Padding SM",
        description: "Padding of small header" },
      { name: "headerPaddingLG", valueType: "string", label: "Header Padding LG",
        description: "Padding of large header" },
      { name: "headerBg", valueType: "color-hex", label: "Header Bg",
        description: "Background of header" },
      { name: "contentPadding", valueType: "string", label: "Content Padding",
        description: "Padding of content" },
      { name: "contentPaddingSM", valueType: "string", label: "Content Padding SM",
        description: "Padding of small content" },
      { name: "contentPaddingLG", valueType: "string", label: "Content Padding LG",
        description: "Padding of large content" },
      { name: "contentBg", valueType: "color-hex", label: "Content Bg",
        description: "Background of content" },
      { name: "borderlessContentPadding", valueType: "string", label: "Borderless Content Padding",
        description: "Padding of content in borderless style" },
      { name: "borderlessContentBg", valueType: "color-hex", label: "Borderless Content Bg",
        description: "Background of content in borderless style" },
    ],
  },
  {
    slug: "date-picker",
    component: "DatePicker",
    title: "Date Picker",
    fields: [
      { name: "presetsWidth", valueType: "number", label: "Presets Width",
        description: "Width of preset area" },
      { name: "presetsMaxWidth", valueType: "number", label: "Presets Max Width",
        description: "Max width of preset area" },
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of popup" },
      { name: "paddingInline", valueType: "number", label: "Padding Inline",
        description: "Horizontal padding of input" },
      { name: "paddingInlineSM", valueType: "number", label: "Padding Inline SM",
        description: "Horizontal padding of small input" },
      { name: "paddingInlineLG", valueType: "number", label: "Padding Inline LG",
        description: "Horizontal padding of large input" },
      { name: "paddingBlock", valueType: "number", label: "Padding Block",
        description: "Vertical padding of input" },
      { name: "paddingBlockSM", valueType: "number", label: "Padding Block SM",
        description: "Vertical padding of small input" },
      { name: "paddingBlockLG", valueType: "number", label: "Padding Block LG",
        description: "Vertical padding of large input" },
      { name: "addonBg", valueType: "color-hex", label: "Addon Bg",
        description: "Background color of addon" },
      { name: "hoverBorderColor", valueType: "color-hex", label: "Hover Border Color",
        description: "Hover border color" },
      { name: "activeBorderColor", valueType: "color-hex", label: "Active Border Color",
        description: "Active border color" },
      { name: "activeShadow", valueType: "string", label: "Active Shadow",
        description: "Box-shadow when active" },
      { name: "errorActiveShadow", valueType: "string", label: "Error Active Shadow",
        description: "Box-shadow when active in error status" },
      { name: "warningActiveShadow", valueType: "string", label: "Warning Active Shadow",
        description: "Box-shadow when active in warning status" },
      { name: "hoverBg", valueType: "color-hex", label: "Hover Bg",
        description: "Background color when the input box hovers" },
      { name: "activeBg", valueType: "color-hex", label: "Active Bg",
        description: "Background color when the input box is activated" },
      { name: "inputFontSize", valueType: "number", label: "Input Font Size",
        description: "Font size" },
      { name: "inputFontSizeLG", valueType: "number", label: "Input Font Size LG",
        description: "Font size of large" },
      { name: "inputFontSizeSM", valueType: "number", label: "Input Font Size SM",
        description: "Font size of small" },
      { name: "cellHoverBg", valueType: "color-hex", label: "Cell Hover Bg",
        description: "Background color of cell hover state" },
      { name: "cellActiveWithRangeBg", valueType: "color-hex", label: "Cell Active With Range Bg",
        description: "Background color of cell in range" },
      { name: "cellHoverWithRangeBg", valueType: "color-hex", label: "Cell Hover With Range Bg",
        description: "Background color of hovered cell in range" },
      { name: "cellBgDisabled", valueType: "color-hex", label: "Cell Bg Disabled",
        description: "Background color of disabled cell" },
      { name: "cellRangeBorderColor", valueType: "color-hex", label: "Cell Range Border Color",
        description: "Border color of cell in range when picking" },
      { name: "timeColumnWidth", valueType: "number", label: "Time Column Width",
        description: "Width of time column" },
      { name: "timeColumnHeight", valueType: "number", label: "Time Column Height",
        description: "Height of time column" },
      { name: "timeCellHeight", valueType: "number", label: "Time Cell Height",
        description: "Height of time cell" },
      { name: "cellHeight", valueType: "number", label: "Cell Height",
        description: "Height of cell" },
      { name: "cellWidth", valueType: "number", label: "Cell Width",
        description: "Width of cell" },
      { name: "textHeight", valueType: "number", label: "Text Height",
        description: "Height of cell text" },
      { name: "withoutTimeCellHeight", valueType: "number", label: "Without Time Cell Height",
        description: "Height of decade/year/quarter/month/week cell" },
      { name: "multipleItemBg", valueType: "color-hex", label: "Multiple Item Bg",
        description: "Background color of multiple tag" },
      { name: "multipleItemBorderColor", valueType: "color-hex", label: "Multiple Item Border Color",
        description: "Border color of multiple tag" },
      { name: "multipleItemHeight", valueType: "number", label: "Multiple Item Height",
        description: "Height of multiple tag" },
      { name: "multipleItemHeightSM", valueType: "number", label: "Multiple Item Height SM",
        description: "Height of multiple tag with small size" },
      { name: "multipleItemHeightLG", valueType: "number", label: "Multiple Item Height LG",
        description: "Height of multiple tag with large size" },
      { name: "multipleSelectorBgDisabled", valueType: "color-hex", label: "Multiple Selector Bg Disabled",
        description: "Background color of multiple selector when disabled" },
      { name: "multipleItemColorDisabled", valueType: "color-hex", label: "Multiple Item Color Disabled",
        description: "Text color of multiple tag when disabled" },
      { name: "multipleItemBorderColorDisabled", valueType: "color-hex", label: "Multiple Item Border Color Disabled",
        description: "Border color of multiple tag when disabled" },
    ],
  },
  {
    slug: "descriptions",
    component: "Descriptions",
    title: "Descriptions",
    fields: [
      { name: "labelBg", valueType: "color-hex", label: "Label Bg",
        description: "Background color of label" },
      { name: "labelColor", valueType: "color-hex", label: "Label Color",
        description: "Text color of label" },
      { name: "titleColor", valueType: "color-hex", label: "Title Color",
        description: "Text color of title" },
      { name: "titleMarginBottom", valueType: "number", label: "Title Margin Bottom",
        description: "Bottom margin of title" },
      { name: "itemPaddingBottom", valueType: "number", label: "Item Padding Bottom",
        description: "Bottom padding of item" },
      { name: "itemPaddingEnd", valueType: "number", label: "Item Padding End",
        description: "End padding of item" },
      { name: "colonMarginRight", valueType: "number", label: "Colon Margin Right",
        description: "Right margin of colon" },
      { name: "colonMarginLeft", valueType: "number", label: "Colon Margin Left",
        description: "Left margin of colon" },
      { name: "contentColor", valueType: "color-hex", label: "Content Color",
        description: "Text color of content" },
      { name: "extraColor", valueType: "color-hex", label: "Extra Color",
        description: "Text color of extra area" },
    ],
  },
  {
    slug: "divider",
    component: "Divider",
    title: "Divider",
    fields: [
      { name: "textPaddingInline", valueType: "string", label: "Text Padding Inline",
        description: "Horizontal padding of text" },
      { name: "orientationMargin", valueType: "string", label: "Orientation Margin",
        description: "Distance between text and edge, which should be a number between 0 and 1." },
      { name: "verticalMarginInline", valueType: "string", label: "Vertical Margin Inline",
        description: "Horizontal margin of vertical Divider" },
    ],
  },
  {
    slug: "drawer",
    component: "Drawer",
    title: "Drawer",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of drawer" },
      { name: "footerPaddingBlock", valueType: "number", label: "Footer Padding Block",
        description: "Vertical padding of footer" },
      { name: "footerPaddingInline", valueType: "number", label: "Footer Padding Inline",
        description: "Horizontal padding of footer" },
      { name: "draggerSize", valueType: "number", label: "Dragger Size",
        description: "Size of resize handle" },
    ],
  },
  {
    slug: "dropdown",
    component: "Dropdown",
    title: "Dropdown",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of dropdown" },
      { name: "paddingBlock", valueType: "string", label: "Padding Block",
        description: "Vertical padding of dropdown" },
    ],
  },
  {
    slug: "form",
    component: "Form",
    title: "Form",
    fields: [
      { name: "labelRequiredMarkColor", valueType: "color-hex", label: "Label Required Mark Color",
        description: "Required mark color" },
      { name: "labelColor", valueType: "color-hex", label: "Label Color",
        description: "Label color" },
      { name: "labelFontSize", valueType: "number", label: "Label Font Size",
        description: "Label font size" },
      { name: "labelHeight", valueType: "string", label: "Label Height",
        description: "Label height" },
      { name: "labelColonMarginInlineStart", valueType: "number", label: "Label Colon Margin Inline Start",
        description: "Label colon margin-inline-start" },
      { name: "labelColonMarginInlineEnd", valueType: "number", label: "Label Colon Margin Inline End",
        description: "Label colon margin-inline-end" },
      { name: "itemMarginBottom", valueType: "number", label: "Item Margin Bottom",
        description: "Form item margin bottom" },
      { name: "inlineItemMarginBottom", valueType: "number", label: "Inline Item Margin Bottom",
        description: "Inline layout form item margin bottom" },
      { name: "verticalLabelPadding", valueType: "string", label: "Vertical Label Padding",
        description: "Vertical layout label padding" },
      { name: "verticalLabelMargin", valueType: "string", label: "Vertical Label Margin",
        description: "Vertical layout label margin" },
    ],
  },
  {
    slug: "image",
    component: "Image",
    title: "Image",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of preview popup" },
      { name: "previewOperationSize", valueType: "number", label: "Preview Operation Size",
        description: "Size of preview operation icon" },
      { name: "previewOperationColor", valueType: "color-hex", label: "Preview Operation Color",
        description: "Color of preview operation icon" },
      { name: "previewOperationHoverColor", valueType: "color-hex", label: "Preview Operation Hover Color",
        description: "Color of hovered preview operation icon" },
      { name: "previewOperationColorDisabled", valueType: "color-hex", label: "Preview Operation Color Disabled",
        description: "Disabled color of preview operation icon" },
      { name: "progressAnimationDuration", valueType: "string", label: "Progress Animation Duration",
        description: "Base duration of loading animation" },
    ],
  },
  {
    slug: "input",
    component: "Input",
    title: "Input",
    fields: [
      { name: "paddingInline", valueType: "number", label: "Padding Inline",
        description: "Horizontal padding of input" },
      { name: "paddingInlineSM", valueType: "number", label: "Padding Inline SM",
        description: "Horizontal padding of small input" },
      { name: "paddingInlineLG", valueType: "number", label: "Padding Inline LG",
        description: "Horizontal padding of large input" },
      { name: "paddingBlock", valueType: "number", label: "Padding Block",
        description: "Vertical padding of input" },
      { name: "paddingBlockSM", valueType: "number", label: "Padding Block SM",
        description: "Vertical padding of small input" },
      { name: "paddingBlockLG", valueType: "number", label: "Padding Block LG",
        description: "Vertical padding of large input" },
      { name: "addonBg", valueType: "color-hex", label: "Addon Bg",
        description: "Background color of addon" },
      { name: "hoverBorderColor", valueType: "color-hex", label: "Hover Border Color",
        description: "Hover border color" },
      { name: "activeBorderColor", valueType: "color-hex", label: "Active Border Color",
        description: "Active border color" },
      { name: "activeShadow", valueType: "string", label: "Active Shadow",
        description: "Box-shadow when active" },
      { name: "errorActiveShadow", valueType: "string", label: "Error Active Shadow",
        description: "Box-shadow when active in error status" },
      { name: "warningActiveShadow", valueType: "string", label: "Warning Active Shadow",
        description: "Box-shadow when active in warning status" },
      { name: "hoverBg", valueType: "color-hex", label: "Hover Bg",
        description: "Background color when the input box hovers" },
      { name: "activeBg", valueType: "color-hex", label: "Active Bg",
        description: "Background color when the input box is activated" },
      { name: "inputFontSize", valueType: "number", label: "Input Font Size",
        description: "Font size" },
      { name: "inputFontSizeLG", valueType: "number", label: "Input Font Size LG",
        description: "Font size of large" },
      { name: "inputFontSizeSM", valueType: "number", label: "Input Font Size SM",
        description: "Font size of small" },
    ],
  },
  {
    slug: "input-number",
    component: "InputNumber",
    title: "Input Number",
    fields: [
      { name: "controlWidth", valueType: "number", label: "Control Width",
        description: "Width of input" },
      { name: "handleWidth", valueType: "number", label: "Handle Width",
        description: "Width of control button" },
      { name: "handleFontSize", valueType: "number", label: "Handle Font Size",
        description: "Icon size of control button" },
      { name: "handleVisible", valueType: "string", label: "Handle Visible",
        description: "Handle visible" },
      { name: "handleBg", valueType: "color-hex", label: "Handle Bg",
        description: "Background color of handle" },
      { name: "handleActiveBg", valueType: "color-hex", label: "Handle Active Bg",
        description: "Active background color of handle" },
      { name: "handleHoverColor", valueType: "color-hex", label: "Handle Hover Color",
        description: "Hover color of handle" },
      { name: "handleBorderColor", valueType: "color-hex", label: "Handle Border Color",
        description: "Border color of handle" },
      { name: "filledHandleBg", valueType: "color-hex", label: "Filled Handle Bg",
        description: "Background color of handle in filled variant" },
      { name: "paddingInline", valueType: "number", label: "Padding Inline",
        description: "Horizontal padding of input" },
      { name: "paddingInlineSM", valueType: "number", label: "Padding Inline SM",
        description: "Horizontal padding of small input" },
      { name: "paddingInlineLG", valueType: "number", label: "Padding Inline LG",
        description: "Horizontal padding of large input" },
      { name: "paddingBlock", valueType: "number", label: "Padding Block",
        description: "Vertical padding of input" },
      { name: "paddingBlockSM", valueType: "number", label: "Padding Block SM",
        description: "Vertical padding of small input" },
      { name: "paddingBlockLG", valueType: "number", label: "Padding Block LG",
        description: "Vertical padding of large input" },
      { name: "addonBg", valueType: "color-hex", label: "Addon Bg",
        description: "Background color of addon" },
      { name: "hoverBorderColor", valueType: "color-hex", label: "Hover Border Color",
        description: "Hover border color" },
      { name: "activeBorderColor", valueType: "color-hex", label: "Active Border Color",
        description: "Active border color" },
      { name: "activeShadow", valueType: "string", label: "Active Shadow",
        description: "Box-shadow when active" },
      { name: "errorActiveShadow", valueType: "string", label: "Error Active Shadow",
        description: "Box-shadow when active in error status" },
      { name: "warningActiveShadow", valueType: "string", label: "Warning Active Shadow",
        description: "Box-shadow when active in warning status" },
      { name: "hoverBg", valueType: "color-hex", label: "Hover Bg",
        description: "Background color when the input box hovers" },
      { name: "activeBg", valueType: "color-hex", label: "Active Bg",
        description: "Background color when the input box is activated" },
      { name: "inputFontSize", valueType: "number", label: "Input Font Size",
        description: "Font size" },
      { name: "inputFontSizeLG", valueType: "number", label: "Input Font Size LG",
        description: "Font size of large" },
      { name: "inputFontSizeSM", valueType: "number", label: "Input Font Size SM",
        description: "Font size of small" },
    ],
  },
  {
    slug: "layout",
    component: "Layout",
    title: "Layout",
    fields: [
      { name: "bodyBg", valueType: "color-hex", label: "Body Bg",
        description: "Background Color of body" },
      { name: "headerBg", valueType: "color-hex", label: "Header Bg",
        description: "Background Color of header" },
      { name: "headerHeight", valueType: "string", label: "Header Height",
        description: "Height of header" },
      { name: "headerPadding", valueType: "string", label: "Header Padding",
        description: "Padding of header" },
      { name: "headerColor", valueType: "color-hex", label: "Header Color",
        description: "Text color of header" },
      { name: "footerPadding", valueType: "string", label: "Footer Padding",
        description: "Padding of footer" },
      { name: "footerBg", valueType: "color-hex", label: "Footer Bg",
        description: "Background Color of footer" },
      { name: "siderBg", valueType: "color-hex", label: "Sider Bg",
        description: "Background Color of sider" },
      { name: "triggerHeight", valueType: "string", label: "Trigger Height",
        description: "Height of sider trigger" },
      { name: "triggerBg", valueType: "color-hex", label: "Trigger Bg",
        description: "Background Color of sider trigger" },
      { name: "triggerColor", valueType: "color-hex", label: "Trigger Color",
        description: "Color of sider trigger" },
      { name: "zeroTriggerWidth", valueType: "number", label: "Zero Trigger Width",
        description: "Width of sider trigger when collapse is 0" },
      { name: "zeroTriggerHeight", valueType: "number", label: "Zero Trigger Height",
        description: "Height of sider trigger when collapse is 0" },
      { name: "lightSiderBg", valueType: "color-hex", label: "Light Sider Bg",
        description: "Background Color of light theme sider" },
      { name: "lightTriggerBg", valueType: "color-hex", label: "Light Trigger Bg",
        description: "Background Color of light theme sider trigger" },
      { name: "lightTriggerColor", valueType: "color-hex", label: "Light Trigger Color",
        description: "Color of light theme sider trigger" },
    ],
  },
  {
    slug: "list",
    component: "List",
    title: "List",
    fields: [
      { name: "contentWidth", valueType: "string", label: "Content Width",
        description: "Width of content" },
      { name: "itemPaddingLG", valueType: "string", label: "Item Padding LG",
        description: "Padding of large item" },
      { name: "itemPaddingSM", valueType: "string", label: "Item Padding SM",
        description: "Padding of small item" },
      { name: "itemPadding", valueType: "string", label: "Item Padding",
        description: "Padding of item" },
      { name: "headerBg", valueType: "color-hex", label: "Header Bg",
        description: "Background color of header" },
      { name: "footerBg", valueType: "color-hex", label: "Footer Bg",
        description: "Background color of footer" },
      { name: "emptyTextPadding", valueType: "string", label: "Empty Text Padding",
        description: "Padding of empty text" },
      { name: "metaMarginBottom", valueType: "string", label: "Meta Margin Bottom",
        description: "Margin bottom of meta" },
      { name: "avatarMarginRight", valueType: "string", label: "Avatar Margin Right",
        description: "Right margin of avatar" },
      { name: "titleMarginBottom", valueType: "string", label: "Title Margin Bottom",
        description: "Margin bottom of title" },
      { name: "descriptionFontSize", valueType: "number", label: "Description Font Size",
        description: "Font size of description" },
    ],
  },
  {
    slug: "mentions",
    component: "Mentions",
    title: "Mentions",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of popup" },
      { name: "dropdownHeight", valueType: "string", label: "Dropdown Height",
        description: "Height of popup" },
      { name: "controlItemWidth", valueType: "string", label: "Control Item Width",
        description: "Height of menu item" },
      { name: "paddingInline", valueType: "number", label: "Padding Inline",
        description: "Horizontal padding of input" },
      { name: "paddingInlineSM", valueType: "number", label: "Padding Inline SM",
        description: "Horizontal padding of small input" },
      { name: "paddingInlineLG", valueType: "number", label: "Padding Inline LG",
        description: "Horizontal padding of large input" },
      { name: "paddingBlock", valueType: "number", label: "Padding Block",
        description: "Vertical padding of input" },
      { name: "paddingBlockSM", valueType: "number", label: "Padding Block SM",
        description: "Vertical padding of small input" },
      { name: "paddingBlockLG", valueType: "number", label: "Padding Block LG",
        description: "Vertical padding of large input" },
      { name: "addonBg", valueType: "color-hex", label: "Addon Bg",
        description: "Background color of addon" },
      { name: "hoverBorderColor", valueType: "color-hex", label: "Hover Border Color",
        description: "Hover border color" },
      { name: "activeBorderColor", valueType: "color-hex", label: "Active Border Color",
        description: "Active border color" },
      { name: "activeShadow", valueType: "string", label: "Active Shadow",
        description: "Box-shadow when active" },
      { name: "errorActiveShadow", valueType: "string", label: "Error Active Shadow",
        description: "Box-shadow when active in error status" },
      { name: "warningActiveShadow", valueType: "string", label: "Warning Active Shadow",
        description: "Box-shadow when active in warning status" },
      { name: "hoverBg", valueType: "color-hex", label: "Hover Bg",
        description: "Background color when the input box hovers" },
      { name: "activeBg", valueType: "color-hex", label: "Active Bg",
        description: "Background color when the input box is activated" },
      { name: "inputFontSize", valueType: "number", label: "Input Font Size",
        description: "Font size" },
      { name: "inputFontSizeLG", valueType: "number", label: "Input Font Size LG",
        description: "Font size of large" },
      { name: "inputFontSizeSM", valueType: "number", label: "Input Font Size SM",
        description: "Font size of small" },
    ],
  },
  {
    slug: "menu",
    component: "Menu",
    title: "Menu",
    fields: [
      { name: "dropdownWidth", valueType: "string", label: "Dropdown Width",
        description: "Width of popup menu" },
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of popup menu" },
      { name: "groupTitleColor", valueType: "color-hex", label: "Group Title Color",
        description: "Color of group title text" },
      { name: "groupTitleLineHeight", valueType: "string", label: "Group Title Line Height",
        description: "line-height of group title" },
      { name: "groupTitleFontSize", valueType: "number", label: "Group Title Font Size",
        description: "font-size of group title" },
      { name: "itemBorderRadius", valueType: "number", label: "Item Border Radius",
        description: "Radius of menu item" },
      { name: "subMenuItemBorderRadius", valueType: "number", label: "Sub Menu Item Border Radius",
        description: "Radius of sub-menu item" },
      { name: "itemColor", valueType: "color-hex", label: "Item Color",
        description: "Color of menu item text" },
      { name: "itemHoverColor", valueType: "color-hex", label: "Item Hover Color",
        description: "Hover color of menu item text" },
      { name: "horizontalItemHoverColor", valueType: "color-hex", label: "Horizontal Item Hover Color",
        description: "Hover color of horizontal menu item text" },
      { name: "itemSelectedColor", valueType: "color-hex", label: "Item Selected Color",
        description: "Color of selected menu item text" },
      { name: "subMenuItemSelectedColor", valueType: "color-hex", label: "Sub Menu Item Selected Color",
        description: "Color of submenu title when submenu has selected item" },
      { name: "horizontalItemSelectedColor", valueType: "color-hex", label: "Horizontal Item Selected Color",
        description: "Color of selected horizontal menu item text" },
      { name: "itemDisabledColor", valueType: "color-hex", label: "Item Disabled Color",
        description: "Color of disabled menu item text" },
      { name: "dangerItemColor", valueType: "color-hex", label: "Danger Item Color",
        description: "Color of danger menu item text" },
      { name: "dangerItemHoverColor", valueType: "color-hex", label: "Danger Item Hover Color",
        description: "Hover color of danger menu item text" },
      { name: "dangerItemSelectedColor", valueType: "color-hex", label: "Danger Item Selected Color",
        description: "Color of selected danger menu item text" },
      { name: "dangerItemActiveBg", valueType: "color-hex", label: "Danger Item Active Bg",
        description: "Background color of danger menu item when active" },
      { name: "dangerItemSelectedBg", valueType: "color-hex", label: "Danger Item Selected Bg",
        description: "Background color of selected danger menu item" },
      { name: "itemBg", valueType: "color-hex", label: "Item Bg" },
      { name: "itemHoverBg", valueType: "color-hex", label: "Item Hover Bg",
        description: "Background color of menu item when hover" },
      { name: "subMenuItemBg", valueType: "color-hex", label: "Sub Menu Item Bg",
        description: "Background color of sub-menu item" },
      { name: "itemActiveBg", valueType: "color-hex", label: "Item Active Bg",
        description: "Background color of menu item when active" },
      { name: "itemSelectedBg", valueType: "color-hex", label: "Item Selected Bg",
        description: "Background color of menu item when selected" },
      { name: "horizontalItemSelectedBg", valueType: "color-hex", label: "Horizontal Item Selected Bg",
        description: "Background color of horizontal menu item when selected" },
      { name: "activeBarWidth", valueType: "string", label: "Active Bar Width",
        description: "Width of menu item active bar" },
      { name: "activeBarHeight", valueType: "number", label: "Active Bar Height",
        description: "Height of menu item active bar" },
      { name: "activeBarBorderWidth", valueType: "string", label: "Active Bar Border Width",
        description: "Border width of menu item active bar" },
      { name: "itemMarginInline", valueType: "number", label: "Item Margin Inline",
        description: "Horizontal margin of menu item" },
      { name: "horizontalItemHoverBg", valueType: "color-hex", label: "Horizontal Item Hover Bg",
        description: "Background color of horizontal menu item when hover" },
      { name: "horizontalItemBorderRadius", valueType: "number", label: "Horizontal Item Border Radius",
        description: "Border radius of horizontal menu item" },
      { name: "itemHeight", valueType: "string", label: "Item Height",
        description: "Height of menu item" },
      { name: "collapsedWidth", valueType: "string", label: "Collapsed Width",
        description: "Width when collapsed" },
      { name: "popupBg", valueType: "color-hex", label: "Popup Bg",
        description: "Background color of popup" },
      { name: "itemMarginBlock", valueType: "string", label: "Item Margin Block",
        description: "margin-block of menu item" },
      { name: "itemPaddingInline", valueType: "string", label: "Item Padding Inline",
        description: "padding-inline of menu item" },
      { name: "horizontalLineHeight", valueType: "string", label: "Horizontal Line Height",
        description: "LineHeight of horizontal menu item" },
      { name: "iconMarginInlineEnd", valueType: "string", label: "Icon Margin Inline End",
        description: "Spacing between icon and text" },
      { name: "iconSize", valueType: "number", label: "Icon Size",
        description: "Size of icon" },
      { name: "collapsedIconSize", valueType: "number", label: "Collapsed Icon Size",
        description: "Size of icon when collapsed" },
      { name: "darkPopupBg", valueType: "color-hex", label: "Dark Popup Bg",
        description: "The background color of the overlay menu in dark mode." },
      { name: "darkItemColor", valueType: "color-hex", label: "Dark Item Color",
        description: "Color of menu item text in dark mode" },
      { name: "darkDangerItemColor", valueType: "color-hex", label: "Dark Danger Item Color",
        description: "Color of danger menu item text in dark mode" },
      { name: "darkItemBg", valueType: "color-hex", label: "Dark Item Bg",
        description: "Background of menu item in dark mode" },
      { name: "darkSubMenuItemBg", valueType: "color-hex", label: "Dark Sub Menu Item Bg",
        description: "Background of submenu item in dark mode" },
      { name: "darkItemSelectedColor", valueType: "color-hex", label: "Dark Item Selected Color",
        description: "Color of selected menu item in dark mode" },
      { name: "darkItemSelectedBg", valueType: "color-hex", label: "Dark Item Selected Bg",
        description: "Background of active menu item in dark mode" },
      { name: "darkItemHoverBg", valueType: "color-hex", label: "Dark Item Hover Bg",
        description: "Background of hovered menu item in dark mode" },
      { name: "darkGroupTitleColor", valueType: "color-hex", label: "Dark Group Title Color",
        description: "Color of group title text in dark mode" },
      { name: "darkItemHoverColor", valueType: "color-hex", label: "Dark Item Hover Color",
        description: "Color of hovered menu item in dark mode" },
      { name: "darkItemDisabledColor", valueType: "color-hex", label: "Dark Item Disabled Color",
        description: "Color of disabled menu item in dark mode" },
      { name: "darkDangerItemSelectedBg", valueType: "color-hex", label: "Dark Danger Item Selected Bg",
        description: "Background of active danger menu item in dark mode" },
      { name: "darkDangerItemHoverColor", valueType: "color-hex", label: "Dark Danger Item Hover Color",
        description: "Background of hovered danger menu item in dark mode" },
      { name: "darkDangerItemSelectedColor", valueType: "color-hex", label: "Dark Danger Item Selected Color",
        description: "Color of selected danger menu item in dark mode" },
      { name: "darkDangerItemActiveBg", valueType: "color-hex", label: "Dark Danger Item Active Bg",
        description: "Background of active danger menu item in dark mode" },
    ],
  },
  {
    slug: "message",
    component: "Message",
    title: "Message",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of Message" },
      { name: "contentBg", valueType: "color-hex", label: "Content Bg",
        description: "Background color of Message" },
      { name: "contentPadding", valueType: "string", label: "Content Padding",
        description: "Padding of Message" },
    ],
  },
  {
    slug: "modal",
    component: "Modal",
    title: "Modal",
    fields: [
      { name: "headerBg", valueType: "color-hex", label: "Header Bg",
        description: "Background color of header" },
      { name: "titleLineHeight", valueType: "string", label: "Title Line Height",
        description: "Line height of title" },
      { name: "titleFontSize", valueType: "string", label: "Title Font Size",
        description: "Font size of title" },
      { name: "titleColor", valueType: "color-hex", label: "Title Color",
        description: "Font color of title" },
      { name: "contentBg", valueType: "color-hex", label: "Content Bg",
        description: "Background color of content" },
      { name: "footerBg", valueType: "color-hex", label: "Footer Bg",
        description: "Background color of footer" },
    ],
  },
  {
    slug: "notification",
    component: "Notification",
    title: "Notification",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of Notification" },
      { name: "width", valueType: "string", label: "Width",
        description: "Width of Notification" },
      { name: "progressBg", valueType: "color-hex", label: "Progress Bg",
        description: "Background color of Notification progress bar" },
      { name: "colorSuccessBg", valueType: "string", label: "Color Success Bg",
        description: "Background color of success notification container" },
      { name: "colorErrorBg", valueType: "string", label: "Color Error Bg",
        description: "Background color of error notification container" },
      { name: "colorInfoBg", valueType: "string", label: "Color Info Bg",
        description: "Background color of info notification container" },
      { name: "colorWarningBg", valueType: "string", label: "Color Warning Bg",
        description: "Background color of warning notification container" },
    ],
  },
  {
    slug: "pagination",
    component: "Pagination",
    title: "Pagination",
    fields: [
      { name: "itemBg", valueType: "color-hex", label: "Item Bg",
        description: "Background color of Pagination item" },
      { name: "itemSize", valueType: "number", label: "Item Size",
        description: "Size of Pagination item" },
      { name: "itemSizeSM", valueType: "number", label: "Item Size SM",
        description: "Size of small Pagination item" },
      { name: "itemSizeLG", valueType: "number", label: "Item Size LG",
        description: "Size of large Pagination item" },
      { name: "itemActiveBg", valueType: "color-hex", label: "Item Active Bg",
        description: "Background color of active Pagination item" },
      { name: "itemActiveColor", valueType: "color-hex", label: "Item Active Color",
        description: "Text color of active Pagination item" },
      { name: "itemActiveColorHover", valueType: "color-hex", label: "Item Active Color Hover",
        description: "Text color of active Pagination item hover" },
      { name: "itemLinkBg", valueType: "color-hex", label: "Item Link Bg",
        description: "Background color of Pagination item link" },
      { name: "itemActiveBgDisabled", valueType: "color-hex", label: "Item Active Bg Disabled",
        description: "Background color of disabled active Pagination item" },
      { name: "itemActiveColorDisabled", valueType: "color-hex", label: "Item Active Color Disabled",
        description: "Text color of disabled active Pagination item" },
      { name: "itemInputBg", valueType: "color-hex", label: "Item Input Bg",
        description: "Background color of input" },
      { name: "miniOptionsSizeChangerTop", valueType: "number", label: "Mini Options Size Changer Top",
        description: "Top of Pagination size changer" },
    ],
  },
  {
    slug: "popconfirm",
    component: "Popconfirm",
    title: "Popconfirm",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of Popconfirm" },
    ],
  },
  {
    slug: "popover",
    component: "Popover",
    title: "Popover",
    fields: [
      { name: "titleMinWidth", valueType: "string", label: "Title Min Width",
        description: "Min width of Popover title" },
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of Popover" },
    ],
  },
  {
    slug: "progress",
    component: "Progress",
    title: "Progress",
    fields: [
      { name: "defaultColor", valueType: "color-hex", label: "Default Color",
        description: "Default color of progress bar" },
      { name: "remainingColor", valueType: "color-hex", label: "Remaining Color",
        description: "Color of remaining part of progress bar" },
      { name: "circleTextColor", valueType: "color-hex", label: "Circle Text Color",
        description: "Text color of circular progress bar" },
      { name: "lineBorderRadius", valueType: "number", label: "Line Border Radius",
        description: "Border radius of line progress bar" },
      { name: "circleTextFontSize", valueType: "string", label: "Circle Text Font Size",
        description: "Text size of circular progress bar" },
      { name: "circleIconFontSize", valueType: "string", label: "Circle Icon Font Size",
        description: "Icon size of circular progress bar" },
    ],
  },
  {
    slug: "radio",
    component: "Radio",
    title: "Radio",
    fields: [
      { name: "radioSize", valueType: "number", label: "Radio Size",
        description: "Radio size" },
      { name: "dotSize", valueType: "number", label: "Dot Size",
        description: "Size of Radio dot" },
      { name: "dotColorDisabled", valueType: "color-hex", label: "Dot Color Disabled",
        description: "Color of disabled Radio dot" },
      { name: "buttonBg", valueType: "color-hex", label: "Button Bg",
        description: "Background color of Radio button" },
      { name: "buttonCheckedBg", valueType: "color-hex", label: "Button Checked Bg",
        description: "Background color of checked Radio button" },
      { name: "buttonColor", valueType: "color-hex", label: "Button Color",
        description: "Color of Radio button text" },
      { name: "buttonPaddingInline", valueType: "number", label: "Button Padding Inline",
        description: "Horizontal padding of Radio button" },
      { name: "buttonCheckedBgDisabled", valueType: "color-hex", label: "Button Checked Bg Disabled",
        description: "Background color of checked and disabled Radio button" },
      { name: "buttonCheckedColorDisabled", valueType: "color-hex", label: "Button Checked Color Disabled",
        description: "Color of checked and disabled Radio button text" },
      { name: "buttonSolidCheckedColor", valueType: "color-hex", label: "Button Solid Checked Color",
        description: "Color of checked solid Radio button text" },
      { name: "buttonSolidCheckedBg", valueType: "color-hex", label: "Button Solid Checked Bg",
        description: "Background color of checked solid Radio button text" },
      { name: "buttonSolidCheckedHoverBg", valueType: "color-hex", label: "Button Solid Checked Hover Bg",
        description: "Background color of checked solid Radio button text when hover" },
      { name: "buttonSolidCheckedActiveBg", valueType: "color-hex", label: "Button Solid Checked Active Bg",
        description: "Background color of checked solid Radio button text when active" },
      { name: "wrapperMarginInlineEnd", valueType: "number", label: "Wrapper Margin Inline End",
        description: "Margin right of Radio button" },
    ],
  },
  {
    slug: "rate",
    component: "Rate",
    title: "Rate",
    fields: [
      { name: "starColor", valueType: "color-hex", label: "Star Color",
        description: "Star color" },
      { name: "starSize", valueType: "number", label: "Star Size",
        description: "Star size" },
      { name: "starSizeSM", valueType: "number", label: "Star Size SM",
        description: "Small star size" },
      { name: "starSizeLG", valueType: "number", label: "Star Size LG",
        description: "Large star size" },
      { name: "starHoverScale", valueType: "string", label: "Star Hover Scale",
        description: "Scale of star when hover" },
      { name: "starBg", valueType: "color-hex", label: "Star Bg",
        description: "Star background color" },
    ],
  },
  {
    slug: "result",
    component: "Result",
    title: "Result",
    fields: [
      { name: "titleFontSize", valueType: "string", label: "Title Font Size",
        description: "Title font size" },
      { name: "subtitleFontSize", valueType: "number", label: "Subtitle Font Size",
        description: "Subtitle font size" },
      { name: "iconFontSize", valueType: "string", label: "Icon Font Size",
        description: "Icon size" },
      { name: "extraMargin", valueType: "string", label: "Extra Margin",
        description: "Margin of extra area" },
    ],
  },
  {
    slug: "segmented",
    component: "Segmented",
    title: "Segmented",
    fields: [
      { name: "itemColor", valueType: "color-hex", label: "Item Color",
        description: "Text color of item" },
      { name: "itemHoverColor", valueType: "color-hex", label: "Item Hover Color",
        description: "Text color of item when hover" },
      { name: "itemHoverBg", valueType: "color-hex", label: "Item Hover Bg",
        description: "Background color of item when hover" },
      { name: "itemActiveBg", valueType: "color-hex", label: "Item Active Bg",
        description: "Background color of item when active" },
      { name: "itemSelectedBg", valueType: "color-hex", label: "Item Selected Bg",
        description: "Background color of item when selected" },
      { name: "itemSelectedColor", valueType: "color-hex", label: "Item Selected Color",
        description: "Text color of item when selected" },
      { name: "trackPadding", valueType: "string", label: "Track Padding",
        description: "Padding of Segmented container" },
      { name: "trackBg", valueType: "color-hex", label: "Track Bg",
        description: "Background of Segmented container" },
    ],
  },
  {
    slug: "select",
    component: "Select",
    title: "Select",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of dropdown" },
      { name: "optionSelectedColor", valueType: "color-hex", label: "Option Selected Color",
        description: "Text color when option is selected" },
      { name: "optionSelectedFontWeight", valueType: "string", label: "Option Selected Font Weight",
        description: "Font weight when option is selected" },
      { name: "optionSelectedBg", valueType: "color-hex", label: "Option Selected Bg",
        description: "Background color when option is selected" },
      { name: "optionActiveBg", valueType: "color-hex", label: "Option Active Bg",
        description: "Background color when option is active" },
      { name: "optionPadding", valueType: "string", label: "Option Padding",
        description: "Padding of option" },
      { name: "optionFontSize", valueType: "number", label: "Option Font Size",
        description: "Font size of option" },
      { name: "optionLineHeight", valueType: "string", label: "Option Line Height",
        description: "Line height of option" },
      { name: "optionHeight", valueType: "number", label: "Option Height",
        description: "Height of option" },
      { name: "selectorBg", valueType: "color-hex", label: "Selector Bg",
        description: "Background color of selector" },
      { name: "clearBg", valueType: "color-hex", label: "Clear Bg",
        description: "Background color of clear button" },
      { name: "singleItemHeightLG", valueType: "number", label: "Single Item Height LG",
        description: "Height of single selected item with large size" },
      { name: "showArrowPaddingInlineEnd", valueType: "number", label: "Show Arrow Padding Inline End",
        description: "Inline end padding of arrow" },
      { name: "hoverBorderColor", valueType: "color-hex", label: "Hover Border Color",
        description: "Hover border color" },
      { name: "activeBorderColor", valueType: "color-hex", label: "Active Border Color",
        description: "Active border color" },
      { name: "activeOutlineColor", valueType: "color-hex", label: "Active Outline Color",
        description: "Active outline color" },
      { name: "multipleItemBg", valueType: "color-hex", label: "Multiple Item Bg",
        description: "Background color of multiple tag" },
      { name: "multipleItemBorderColor", valueType: "color-hex", label: "Multiple Item Border Color",
        description: "Border color of multiple tag" },
      { name: "multipleItemHeight", valueType: "number", label: "Multiple Item Height",
        description: "Height of multiple tag" },
      { name: "multipleItemHeightSM", valueType: "number", label: "Multiple Item Height SM",
        description: "Height of multiple tag with small size" },
      { name: "multipleItemHeightLG", valueType: "number", label: "Multiple Item Height LG",
        description: "Height of multiple tag with large size" },
      { name: "multipleSelectorBgDisabled", valueType: "color-hex", label: "Multiple Selector Bg Disabled",
        description: "Background color of multiple selector when disabled" },
      { name: "multipleItemColorDisabled", valueType: "color-hex", label: "Multiple Item Color Disabled",
        description: "Text color of multiple tag when disabled" },
      { name: "multipleItemBorderColorDisabled", valueType: "color-hex", label: "Multiple Item Border Color Disabled",
        description: "Border color of multiple tag when disabled" },
    ],
  },
  {
    slug: "skeleton",
    component: "Skeleton",
    title: "Skeleton",
    fields: [
      { name: "gradientFromColor", valueType: "color-hex", label: "Gradient From Color",
        description: "Start color of gradient" },
      { name: "gradientToColor", valueType: "color-hex", label: "Gradient To Color",
        description: "End color of gradient" },
      { name: "titleHeight", valueType: "string", label: "Title Height",
        description: "Height of title skeleton" },
      { name: "blockRadius", valueType: "number", label: "Block Radius",
        description: "Border radius of skeleton" },
      { name: "paragraphMarginTop", valueType: "number", label: "Paragraph Margin Top",
        description: "Margin top of paragraph skeleton" },
      { name: "paragraphLiHeight", valueType: "number", label: "Paragraph Li Height",
        description: "Line height of paragraph skeleton" },
    ],
  },
  {
    slug: "slider",
    component: "Slider",
    title: "Slider",
    fields: [
      { name: "controlSize", valueType: "number", label: "Control Size",
        description: "Height of slider" },
      { name: "railSize", valueType: "number", label: "Rail Size",
        description: "Height of rail" },
      { name: "handleSize", valueType: "number", label: "Handle Size",
        description: "Size of handle" },
      { name: "handleSizeHover", valueType: "number", label: "Handle Size Hover",
        description: "Size of handle when hover" },
      { name: "handleLineWidth", valueType: "string", label: "Handle Line Width",
        description: "Border width of handle" },
      { name: "handleLineWidthHover", valueType: "string", label: "Handle Line Width Hover",
        description: "Border width of handle when hover" },
      { name: "dotSize", valueType: "number", label: "Dot Size",
        description: "Size of dot" },
      { name: "railBg", valueType: "color-hex", label: "Rail Bg",
        description: "Background color of rail" },
      { name: "railHoverBg", valueType: "color-hex", label: "Rail Hover Bg",
        description: "Background color of rail when hover" },
      { name: "trackBg", valueType: "color-hex", label: "Track Bg",
        description: "Background color of track" },
      { name: "trackHoverBg", valueType: "color-hex", label: "Track Hover Bg",
        description: "Background color of track when hover" },
      { name: "handleColor", valueType: "color-hex", label: "Handle Color",
        description: "Color of handle" },
      { name: "handleActiveColor", valueType: "color-hex", label: "Handle Active Color",
        description: "Border color of handle when active" },
      { name: "handleActiveOutlineColor", valueType: "color-hex", label: "Handle Active Outline Color",
        description: "Outline color of handle when active" },
      { name: "handleColorDisabled", valueType: "color-hex", label: "Handle Color Disabled",
        description: "Color of handle when disabled" },
      { name: "dotBorderColor", valueType: "color-hex", label: "Dot Border Color",
        description: "Border color of dot" },
      { name: "dotActiveBorderColor", valueType: "color-hex", label: "Dot Active Border Color",
        description: "Border color of dot when active" },
      { name: "trackBgDisabled", valueType: "color-hex", label: "Track Bg Disabled",
        description: "Background color of track when disabled" },
    ],
  },
  {
    slug: "spin",
    component: "Spin",
    title: "Spin",
    fields: [
      { name: "contentHeight", valueType: "string", label: "Content Height",
        description: "Height of content area" },
      { name: "dotSize", valueType: "number", label: "Dot Size",
        description: "Loading icon size" },
      { name: "dotSizeSM", valueType: "number", label: "Dot Size SM",
        description: "Small loading icon size" },
      { name: "dotSizeLG", valueType: "number", label: "Dot Size LG",
        description: "Large loading icon size" },
    ],
  },
  {
    slug: "splitter",
    component: "Splitter",
    title: "Splitter",
    fields: [
      { name: "splitBarDraggableSize", valueType: "number", label: "Split Bar Draggable Size",
        description: "Drag and drop the identity element size" },
      { name: "splitBarSize", valueType: "number", label: "Split Bar Size",
        description: "Drag the element display size" },
      { name: "splitTriggerSize", valueType: "number", label: "Split Trigger Size",
        description: "Drag and drop trigger area size" },
    ],
  },
  {
    slug: "statistic",
    component: "Statistic",
    title: "Statistic",
    fields: [
      { name: "titleFontSize", valueType: "number", label: "Title Font Size",
        description: "Title font size" },
      { name: "contentFontSize", valueType: "string", label: "Content Font Size",
        description: "Content font size" },
    ],
  },
  {
    slug: "steps",
    component: "Steps",
    title: "Steps",
    fields: [
      { name: "customIconSize", valueType: "number", label: "Custom Icon Size",
        description: "Size of custom icon container" },
      { name: "customIconTop", valueType: "number", label: "Custom Icon Top",
        description: "Top of custom icon" },
      { name: "customIconFontSize", valueType: "number", label: "Custom Icon Font Size",
        description: "Font size of custom icon" },
      { name: "iconSize", valueType: "number", label: "Icon Size",
        description: "Size of icon container" },
      { name: "iconTop", valueType: "number", label: "Icon Top",
        description: "Top of icon" },
      { name: "iconFontSize", valueType: "number", label: "Icon Font Size",
        description: "Size of icon" },
      { name: "dotSize", valueType: "number", label: "Dot Size",
        description: "Size of dot" },
      { name: "dotCurrentSize", valueType: "number", label: "Dot Current Size",
        description: "Current size of dot" },
      { name: "navArrowColor", valueType: "color-hex", label: "Nav Arrow Color",
        description: "Color of arrow in nav" },
      { name: "navContentMaxWidth", valueType: "string", label: "Nav Content Max Width",
        description: "Max width of nav content" },
      { name: "iconSizeSM", valueType: "string", label: "Icon Size SM",
        description: "Size of small steps icon" },
    ],
  },
  {
    slug: "switch",
    component: "Switch",
    title: "Switch",
    fields: [
      { name: "trackHeight", valueType: "string", label: "Track Height",
        description: "Height of Switch" },
      { name: "trackHeightSM", valueType: "string", label: "Track Height SM",
        description: "Height of small Switch" },
      { name: "trackMinWidth", valueType: "string", label: "Track Min Width",
        description: "Minimum width of Switch" },
      { name: "trackMinWidthSM", valueType: "string", label: "Track Min Width SM",
        description: "Minimum width of small Switch" },
      { name: "trackPadding", valueType: "number", label: "Track Padding",
        description: "Padding of Switch" },
      { name: "handleBg", valueType: "color-hex", label: "Handle Bg",
        description: "Background color of Switch handle" },
      { name: "handleShadow", valueType: "string", label: "Handle Shadow",
        description: "Shadow of Switch handle" },
      { name: "handleSize", valueType: "number", label: "Handle Size",
        description: "Size of Switch handle" },
      { name: "handleSizeSM", valueType: "number", label: "Handle Size SM",
        description: "Size of small Switch handle" },
      { name: "innerMinMargin", valueType: "number", label: "Inner Min Margin",
        description: "Minimum margin of content area" },
      { name: "innerMaxMargin", valueType: "number", label: "Inner Max Margin",
        description: "Maximum margin of content area" },
      { name: "innerMinMarginSM", valueType: "number", label: "Inner Min Margin SM",
        description: "Minimum margin of content area of small Switch" },
      { name: "innerMaxMarginSM", valueType: "number", label: "Inner Max Margin SM",
        description: "Maximum margin of content area of small Switch" },
    ],
  },
  {
    slug: "table",
    component: "Table",
    title: "Table",
    fields: [
      { name: "headerBg", valueType: "color-hex", label: "Header Bg",
        description: "Background of table header" },
      { name: "headerColor", valueType: "color-hex", label: "Header Color",
        description: "Color of table header text" },
      { name: "headerSortActiveBg", valueType: "color-hex", label: "Header Sort Active Bg",
        description: "Background color of table header when sorted" },
      { name: "headerSortHoverBg", valueType: "color-hex", label: "Header Sort Hover Bg",
        description: "Background color of table header when sorted and hovered" },
      { name: "bodySortBg", valueType: "color-hex", label: "Body Sort Bg",
        description: "Background color of table sorted column" },
      { name: "rowHoverBg", valueType: "color-hex", label: "Row Hover Bg",
        description: "Background color of table hovered row" },
      { name: "rowSelectedBg", valueType: "color-hex", label: "Row Selected Bg",
        description: "Background color of table selected row" },
      { name: "rowSelectedHoverBg", valueType: "color-hex", label: "Row Selected Hover Bg",
        description: "Background color of table selected row when hovered" },
      { name: "rowExpandedBg", valueType: "color-hex", label: "Row Expanded Bg",
        description: "Background color of table expanded row" },
      { name: "cellPaddingBlock", valueType: "number", label: "Cell Padding Block",
        description: "Vertical padding of table cell" },
      { name: "cellPaddingInline", valueType: "number", label: "Cell Padding Inline",
        description: "Horizontal padding of table cell (large size by default)" },
      { name: "cellPaddingBlockMD", valueType: "number", label: "Cell Padding Block MD",
        description: "Vertical padding of table cell (middle size)" },
      { name: "cellPaddingInlineMD", valueType: "number", label: "Cell Padding Inline MD",
        description: "Horizontal padding of table cell (middle size)" },
      { name: "cellPaddingBlockSM", valueType: "number", label: "Cell Padding Block SM",
        description: "Vertical padding of table cell (small size)" },
      { name: "cellPaddingInlineSM", valueType: "number", label: "Cell Padding Inline SM",
        description: "Horizontal padding of table cell (small size)" },
      { name: "borderColor", valueType: "color-hex", label: "Border Color",
        description: "Border color of table" },
      { name: "headerBorderRadius", valueType: "number", label: "Header Border Radius",
        description: "Border radius of table header" },
      { name: "footerBg", valueType: "color-hex", label: "Footer Bg",
        description: "Background of footer" },
      { name: "footerColor", valueType: "color-hex", label: "Footer Color",
        description: "Color of footer text" },
      { name: "cellFontSize", valueType: "number", label: "Cell Font Size",
        description: "Font size of table cell (large size by default)" },
      { name: "cellFontSizeMD", valueType: "number", label: "Cell Font Size MD",
        description: "Font size of table cell (middle size)" },
      { name: "cellFontSizeSM", valueType: "number", label: "Cell Font Size SM",
        description: "Font size of table cell (small size)" },
      { name: "headerSplitColor", valueType: "color-hex", label: "Header Split Color",
        description: "Split border color of table header" },
      { name: "fixedHeaderSortActiveBg", valueType: "color-hex", label: "Fixed Header Sort Active Bg",
        description: "Background color of fixed table header when sorted" },
      { name: "headerFilterHoverBg", valueType: "color-hex", label: "Header Filter Hover Bg",
        description: "Background color of table header filter button when hovered" },
      { name: "filterDropdownMenuBg", valueType: "color-hex", label: "Filter Dropdown Menu Bg",
        description: "Background of filter dropdown menu item" },
      { name: "filterDropdownBg", valueType: "color-hex", label: "Filter Dropdown Bg",
        description: "Color of filter dropdown" },
      { name: "expandIconBg", valueType: "color-hex", label: "Expand Icon Bg",
        description: "Background of expand button" },
      { name: "selectionColumnWidth", valueType: "string", label: "Selection Column Width",
        description: "Width of selection column" },
      { name: "stickyScrollBarBg", valueType: "color-hex", label: "Sticky Scroll Bar Bg",
        description: "Background of sticky scrollbar" },
      { name: "stickyScrollBarBorderRadius", valueType: "number", label: "Sticky Scroll Bar Border Radius",
        description: "Border radius of sticky scrollbar" },
    ],
  },
  {
    slug: "tabs",
    component: "Tabs",
    title: "Tabs",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of dropdown menu" },
      { name: "cardBg", valueType: "color-hex", label: "Card Bg",
        description: "Background color of card tab" },
      { name: "cardHeight", valueType: "number", label: "Card Height",
        description: "Height of card tab" },
      { name: "cardHeightSM", valueType: "number", label: "Card Height SM",
        description: "Height of small card tab" },
      { name: "cardHeightLG", valueType: "number", label: "Card Height LG",
        description: "Height of large card tab" },
      { name: "cardPadding", valueType: "string", label: "Card Padding",
        description: "Padding of card tab" },
      { name: "cardPaddingSM", valueType: "string", label: "Card Padding SM",
        description: "Padding of small card tab" },
      { name: "cardPaddingLG", valueType: "string", label: "Card Padding LG",
        description: "Padding of large card tab" },
      { name: "titleFontSize", valueType: "number", label: "Title Font Size",
        description: "Font size of title" },
      { name: "titleFontSizeLG", valueType: "number", label: "Title Font Size LG",
        description: "Font size of large title" },
      { name: "titleFontSizeSM", valueType: "number", label: "Title Font Size SM",
        description: "Font size of small title" },
      { name: "inkBarColor", valueType: "color-hex", label: "Ink Bar Color",
        description: "Color of indicator" },
      { name: "horizontalMargin", valueType: "string", label: "Horizontal Margin",
        description: "Horizontal margin of horizontal tab" },
      { name: "horizontalItemGutter", valueType: "number", label: "Horizontal Item Gutter",
        description: "Horizontal gutter of horizontal tab" },
      { name: "horizontalItemMargin", valueType: "string", label: "Horizontal Item Margin",
        description: "Horizontal margin of horizontal tab item" },
      { name: "horizontalItemMarginRTL", valueType: "string", label: "Horizontal Item Margin RTL",
        description: "Horizontal margin of horizontal tab item (RTL)" },
      { name: "horizontalItemPadding", valueType: "string", label: "Horizontal Item Padding",
        description: "Horizontal padding of horizontal tab item" },
      { name: "horizontalItemPaddingLG", valueType: "string", label: "Horizontal Item Padding LG",
        description: "Horizontal padding of large horizontal tab item" },
      { name: "horizontalItemPaddingSM", valueType: "string", label: "Horizontal Item Padding SM",
        description: "Horizontal padding of small horizontal tab item" },
      { name: "verticalItemPadding", valueType: "string", label: "Vertical Item Padding",
        description: "Vertical padding of vertical tab item" },
      { name: "verticalItemMargin", valueType: "string", label: "Vertical Item Margin",
        description: "Vertical margin of vertical tab item" },
      { name: "itemColor", valueType: "color-hex", label: "Item Color",
        description: "Text color of tab" },
      { name: "itemActiveColor", valueType: "color-hex", label: "Item Active Color",
        description: "Text color of active tab" },
      { name: "itemHoverColor", valueType: "color-hex", label: "Item Hover Color",
        description: "Text color of hover tab" },
      { name: "itemSelectedColor", valueType: "color-hex", label: "Item Selected Color",
        description: "Text color of selected tab" },
      { name: "cardGutter", valueType: "number", label: "Card Gutter",
        description: "Gutter of card tab" },
    ],
  },
  {
    slug: "tag",
    component: "Tag",
    title: "Tag",
    fields: [
      { name: "defaultBg", valueType: "color-hex", label: "Default Bg",
        description: "Default background color" },
      { name: "defaultColor", valueType: "color-hex", label: "Default Color",
        description: "Default text color" },
      { name: "solidTextColor", valueType: "color-hex", label: "Solid Text Color",
        description: "Default text color for solid tag." },
    ],
  },
  {
    slug: "timeline",
    component: "Timeline",
    title: "Timeline",
    fields: [
      { name: "tailColor", valueType: "string", label: "Tail Color",
        description: "Line color" },
      { name: "tailWidth", valueType: "string", label: "Tail Width",
        description: "Line width" },
      { name: "dotBorderWidth", valueType: "string", label: "Dot Border Width",
        description: "Border width of node" },
      { name: "dotSize", valueType: "string", label: "Dot Size",
        description: "Node size" },
      { name: "dotBg", valueType: "string", label: "Dot Bg",
        description: "Background color of node" },
      { name: "itemPaddingBottom", valueType: "string", label: "Item Padding Bottom",
        description: "Bottom padding of item" },
    ],
  },
  {
    slug: "tooltip",
    component: "Tooltip",
    title: "Tooltip",
    fields: [
      { name: "maxWidth", valueType: "number", label: "Max Width",
        description: "Max width of tooltip" },
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "z-index of tooltip" },
    ],
  },
  {
    slug: "tour",
    component: "Tour",
    title: "Tour",
    fields: [
      { name: "zIndexPopup", valueType: "number", label: "Z Index Popup",
        description: "Tour popup z-index" },
      { name: "closeBtnSize", valueType: "number", label: "Close Btn Size",
        description: "Close button size" },
      { name: "primaryPrevBtnBg", valueType: "color-hex", label: "Primary Prev Btn Bg",
        description: "Background color of previous button in primary type" },
      { name: "primaryNextBtnHoverBg", valueType: "color-hex", label: "Primary Next Btn Hover Bg",
        description: "Hover background color of next button in primary type" },
    ],
  },
  {
    slug: "transfer",
    component: "Transfer",
    title: "Transfer",
    fields: [
      { name: "listWidth", valueType: "string", label: "List Width",
        description: "Width of list" },
      { name: "listWidthLG", valueType: "string", label: "List Width LG",
        description: "Width of large list" },
      { name: "listHeight", valueType: "string", label: "List Height",
        description: "Height of list" },
      { name: "itemHeight", valueType: "string", label: "Item Height",
        description: "Height of list item" },
      { name: "itemPaddingBlock", valueType: "string", label: "Item Padding Block",
        description: "Vertical padding of list item" },
      { name: "headerHeight", valueType: "string", label: "Header Height",
        description: "Height of header" },
    ],
  },
  {
    slug: "tree",
    component: "Tree",
    title: "Tree",
    fields: [
      { name: "directoryNodeSelectedColor", valueType: "color-hex", label: "Directory Node Selected Color",
        description: "Text color of selected directory node" },
      { name: "directoryNodeSelectedBg", valueType: "color-hex", label: "Directory Node Selected Bg",
        description: "Background color of selected directory node" },
      { name: "titleHeight", valueType: "number", label: "Title Height",
        description: "Node title height" },
      { name: "switcherSize", valueType: "string", label: "Switcher Size",
        description: "Switcher width of tree" },
      { name: "indentSize", valueType: "string", label: "Indent Size",
        description: "Indent width of tree" },
      { name: "nodeHoverBg", valueType: "color-hex", label: "Node Hover Bg",
        description: "Background color of hovered node" },
      { name: "nodeHoverColor", valueType: "color-hex", label: "Node Hover Color",
        description: "Text color of hovered node" },
      { name: "nodeSelectedBg", valueType: "color-hex", label: "Node Selected Bg",
        description: "Background color of selected node" },
      { name: "nodeSelectedColor", valueType: "color-hex", label: "Node Selected Color",
        description: "Text color of selected node" },
    ],
  },
  {
    slug: "tree-select",
    component: "TreeSelect",
    title: "Tree Select",
    fields: [
      { name: "titleHeight", valueType: "number", label: "Title Height",
        description: "Node title height" },
      { name: "switcherSize", valueType: "string", label: "Switcher Size",
        description: "Switcher width of tree" },
      { name: "indentSize", valueType: "string", label: "Indent Size",
        description: "Indent width of tree" },
      { name: "nodeHoverBg", valueType: "color-hex", label: "Node Hover Bg",
        description: "Background color of hovered node" },
      { name: "nodeHoverColor", valueType: "color-hex", label: "Node Hover Color",
        description: "Text color of hovered node" },
      { name: "nodeSelectedBg", valueType: "color-hex", label: "Node Selected Bg",
        description: "Background color of selected node" },
      { name: "nodeSelectedColor", valueType: "color-hex", label: "Node Selected Color",
        description: "Text color of selected node" },
    ],
  },
  {
    slug: "typography",
    component: "Typography",
    title: "Typography",
    fields: [
      { name: "titleMarginTop", valueType: "string", label: "Title Margin Top",
        description: "Margin top of title" },
      { name: "titleMarginBottom", valueType: "string", label: "Title Margin Bottom",
        description: "Margin bottom of title" },
    ],
  },
  {
    slug: "upload",
    component: "Upload",
    title: "Upload",
    fields: [
      { name: "actionsColor", valueType: "color-hex", label: "Actions Color",
        description: "Action button color" },
      { name: "pictureCardSize", valueType: "number", label: "Picture Card Size",
        description: "Size of list items in card type (affects both picture-card and picture-circle)" },
    ],
  },
]
